// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLqdz8EPB4dC5OE6SZ1KTSNtrBIR_Tbzc',
    appId: '1:961421919288:web:defa0694ba333752fd12cd',
    messagingSenderId: '961421919288',
    projectId: 'royal-frame-969d1',
    authDomain: 'royal-frame-969d1.firebaseapp.com',
    storageBucket: 'royal-frame-969d1.firebasestorage.app',
    measurementId: 'G-T1NKRQ2B0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoqtGMVwhL1-eFA9pJOiymlc94BXBv2So',
    appId: '1:961421919288:android:ea8f1f61aa95325dfd12cd',
    messagingSenderId: '961421919288',
    projectId: 'royal-frame-969d1',
    storageBucket: 'royal-frame-969d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFLSuXIZ3mxnuGRNstVPug5Lt05YN13zM',
    appId: '1:961421919288:ios:f7c4ae147e4c326cfd12cd',
    messagingSenderId: '961421919288',
    projectId: 'royal-frame-969d1',
    storageBucket: 'royal-frame-969d1.firebasestorage.app',
    iosBundleId: 'com.example.royalFrameMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFLSuXIZ3mxnuGRNstVPug5Lt05YN13zM',
    appId: '1:961421919288:ios:f7c4ae147e4c326cfd12cd',
    messagingSenderId: '961421919288',
    projectId: 'royal-frame-969d1',
    storageBucket: 'royal-frame-969d1.firebasestorage.app',
    iosBundleId: 'com.example.royalFrameMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLqdz8EPB4dC5OE6SZ1KTSNtrBIR_Tbzc',
    appId: '1:961421919288:web:a322bd595a549047fd12cd',
    messagingSenderId: '961421919288',
    projectId: 'royal-frame-969d1',
    authDomain: 'royal-frame-969d1.firebaseapp.com',
    storageBucket: 'royal-frame-969d1.firebasestorage.app',
    measurementId: 'G-MM0RQ82F1X',
  );
}
